# Numpy alıştırma soruları 1 ve 2

# Numpy alıştırma soruları 1

In [1]:
import numpy as np

1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin.

In [2]:
arr1 = np.array([[ [12,15,14],[16,17,19] , [20,21,22] ]])

In [3]:
arr1.ndim

3

In [4]:
arr1

array([[[12, 15, 14],
        [16, 17, 19],
        [20, 21, 22]]])

2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

In [6]:
arr2 = np.arange(34,113,6)

In [7]:
arr2

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)

In [16]:
arr3 = np.linspace(50,500,91 , dtype = int)
arr3.size


91

In [ ]:
4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

In [24]:
np.logspace(2 , 5 , num = 8 , base = 10 , dtype = float)

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.

In [27]:
arr4 = np.arange(9).reshape(3,3)
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

In [29]:
np.zeros([6,6] , dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)

In [30]:
np.ones((4,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

In [33]:
np.eye(8,8, dtype = int) # bu fonksiyon satır ve sütun sayısı

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

In [34]:
np.eye(5,5,dtype = int)*3

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

In [35]:
np.random.rand(6)

array([0.32615885, 0.68283207, 0.70515638, 0.78985027, 0.66388001,
       0.54019463])

11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

In [39]:
np.random.seed(101) # her çalıştırmada aynı sonucu verir bu şekilde.
np.random.randint(50,101,10).reshape((5,2))

array([[81, 61],
       [67, 56],
       [73, 61],
       [97, 59],
       [63, 90]])

12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

In [43]:
arr5 = np.random.randint(100,1000,50).reshape(2,5,-1)
arr5

array([[[661, 955, 152, 353, 497],
        [380, 504, 792, 928, 915],
        [470, 385, 928, 409, 495],
        [140, 319, 913, 709, 904],
        [778, 749, 225, 664, 167]],

       [[911, 229, 179, 680, 808],
        [584, 161, 758, 919, 370],
        [512, 187, 658, 152, 244],
        [555, 696, 110, 290, 974],
        [196, 222, 335, 587, 797]]])

In [44]:
arr5.shape

(2, 5, 5)

13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

In [48]:
np.random.seed(1)
arr6 = np.random.randint(0,101,10)
arr6

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [55]:
print(arr6.max())
print(arr6.min())
print(f"array içerisindeki en büyük elemanın sırası : {arr6.argmax()}")
print(f"array içerisindeki en küçük elemanın sırası : {arr6.argmin()}")

79
1
array içerisindeki en büyük elemanın sırası : 6
array içerisindeki en küçük elemanın sırası : 9


14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

In [59]:
np.random.seed(1)
arr7 = np.random.randint(300,501,20).reshape(2,2,-1)
arr7

array([[[337, 440, 372, 437, 433],
        [379, 492, 444, 429, 371]],

       [[434, 325, 478, 320, 401],
        [446, 439, 456, 457, 442]]])

In [68]:
arr7[0][1][1]

492

In [73]:
arr7[1,0,3] 

320

15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [78]:
arr8 = np.arange(51)
arr8[20:35] = 500
arr8

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])

# Numpy Alıştırma Soruları 2

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.

In [80]:
np.arange(30).reshape(15,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [83]:
np.random.randint(0,1000,size = 60 , dtype = int).reshape(3,2,-1)

array([[[493, 506, 271, 745, 493, 392, 759, 401, 918, 760],
        [506, 885, 585, 697, 873, 366, 764, 474, 446,  83]],

       [[ 96, 555, 800, 538, 498, 904, 588, 766, 138, 808],
        [ 34, 316, 649, 758, 997, 838,  86, 454,  19,  56]],

       [[466, 385, 324, 680,  81,  61, 454, 125, 485, 609],
        [914, 980, 474, 855, 918, 299, 820, 741, 970, 968]]])

3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [85]:
np.random.randint(0,10,size = 20).reshape(-1)

array([3, 0, 0, 5, 7, 5, 0, 8, 6, 5, 1, 7, 4, 3, 6, 1, 4, 0, 8, 5])

4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.

In [90]:
arr9 = np.arange(16).reshape(2,-1)
for i in np.nditer(arr9) :
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.

In [96]:
arr10 = np.arange(5,35,5)
arr11 = np.arange(1,7)
print(arr10 + arr11)
print(arr10 - arr11)
print(arr10 * arr11)
print(arr10 / arr11)
print(arr10 // arr11)

[ 6 12 18 24 30 36]
[ 4  8 12 16 20 24]
[  5  20  45  80 125 180]
[5. 5. 5. 5. 5. 5.]
[5 5 5 5 5 5]


6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.

In [116]:
np.random.seed(404)
arr12 = np.random.randint(0,101,10)

print("array elemanları toplamı : {}".format(arr12.sum()))
print("array elemanlarının ortalaması : {}".format(arr12.mean()))
print(f"arraydeki max eleman : {arr12.max()}")
print("array elemanlarının varyansı : {}".format(arr12.var()))
print(f"array elemanlarının standart sapması : {arr12.std()}")

array elemanları toplamı : 595
array elemanlarının ortalaması : 59.5
arraydeki max eleman : 97
array elemanlarının varyansı : 690.05
array elemanlarının standart sapması : 26.268802789621


7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.

In [123]:
arr13 = np.arange(20) ; arr14 = np.arange(500,531)
np.concatenate((arr13,arr14))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.

In [126]:
arr15 = np.arange(15,51)
arr16 = np.arange(10,101)
arr17 = np.concatenate([arr15,arr16])
arr17[25:51] = 888
arr17

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.

In [133]:
arr18 = np.arange(0,40).reshape(8,5)
arr19 = np.arange(320,360).reshape(8,5)
arr20 = np.concatenate([arr18,arr19] , axis = 0)
arr21 = np.concatenate([arr18,arr19] , axis = 1)
arr21

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.

In [135]:
np.stack((arr18,arr19),axis = 2)

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.

In [139]:
arr22 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
indices = np.where(arr22 == 5)[0]
print("5'e eşit olan değerlerin indexleri:", indices)

5'e eşit olan değerlerin indexleri: [ 5 13]


12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.

In [140]:
np.where(arr22%2 ==0)

(array([ 1,  3,  4,  6,  7,  9, 11], dtype=int64),)

13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.

In [141]:
np.where(arr22 > 4)

(array([ 1,  2,  5,  9, 10, 11, 13], dtype=int64),)

14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.

In [142]:
np.where(arr22 % 5 == 0)

(array([ 1,  2,  5, 13], dtype=int64),)

15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin

In [143]:
np.random.randint(85,101,1)

array([90])

16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.

In [144]:
np.random.randint(10,100 , (3,3))

array([[66, 56, 33],
       [85, 37, 13],
       [15, 44, 29]])

17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.

In [148]:
arr23 = np.arange(35,60)
np.random.choice(arr23)

57

18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [150]:
np.random.choice([3, 8, 10, 53],(2,5))

array([[10, 10,  3, 53, 53],
       [10,  3,  3, 10, 53]])